name: property_management_system
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_advanced_networkimage_2: ^2.0.1
  cupertino_icons: ^1.0.2
  either_dart: ^0.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_custom_clippers: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg_provider: ^1.0.3
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^10.1.0
  geolocator: ^8.2.0
  get_it: ^7.2.0
  google_maps_flutter: ^2.1.3
  http: ^0.13.4
  image_picker: ^0.8.5
  intl: ^0.17.0
  loader_overlay: ^2.0.6
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  syncfusion_flutter_sliders: ^20.2.40
  chips_choice: ^2.0.1

  sqflite: ^2.0.2

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

#  flutter_lints: ^1.0.0
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/register_icon/

  fonts:
    - family: MontserratThin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
    - family: ACaslonPro Regular
      fonts:
        - asset: assets/fonts/ACaslonPro-Regular.otf
